esphome:
  name: luba-airlock-esp32
  friendly_name: Luba Airlock ESP32

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "C6WI01uKjsfTEVy0DVnyw7+ZxmYFaL2qWK/+E0OmFek="

ota:
  - platform: esphome
    password: "ff58befdcceb6e27575ff14a4fa1f8ae"

wifi:
  ssid: "SmartDevs"
  password: "35norwich"
#  manual_ip:
#    # Set this to the IP of the ESP
#    static_ip: 192.168.0.186
#    gateway: 192.168.0.1
#    subnet: 255.255.254.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Luba Airlock ESP32"
    password: "12345678"

captive_portal:

